name: gmmap
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - anndata
  - pyyaml
  - tqdm
  - joblib
  - matplotlib
  - pip:
      - -e .[dev,spatial]
